name: Push or PR

on:
  [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_n_test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: rust version
      run: rustc --version
    - name: rustfmt
      run: cargo fmt --all -- --check
    - name: check
      run: cargo check --verbose
    - name: clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Build
      run: cargo build --verbose --tests --all-features
    - name: Test
      run: cargo test --all-features --verbose

  semver:
    name: Check semver
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Check semver
        if: ${{ !cancelled() }}
        uses: obi1kenobi/cargo-semver-checks-action@v2
      - name: Abort on error
        if: ${{ failure() }}
        run: echo "Semver check failed" && false
